### ISSUE TITLE
Error in Export Archive Files For Death Stranding

### ISSUE THREAD

**Issue by rm-NoobInCoding** [Nukem9/HZDCoreEditor#6]
i got this error when i want to export the archives:

```
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at HZDCoreTools.Archive.BuildFileNamesFromPrefetch(PackfileDevice device) in HZDCoreEditor-master\HZDCoreTools\Archive.cs:line 164
   at HZDCoreTools.Archive.ExtractArchive(ExtractArchiveCommand options) in HZDCoreEditor-master\HZDCoreTools\Archive.cs:line 114
   at HZDCoreTools.Program.Run(Object options) in HZDCoreEditor-master\HZDCoreTools\Program.cs:line 70
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at HZDCoreTools.Program.Main(String[] args) in HZDCoreEditor-master\HZDCoreTools\Program.cs:line 56
```

**Comment by dimutch833** [comment]
How did you fixed this?
i have the same
